include:
  - local: /.gitlab/.gitlab-ci.default.yml

.packages:askui-nodejs:
  extends: 
    - .workspace
  before_script:
    - !reference [.workspace, before_script]
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  variables:
    WORKDIR: packages/askui-nodejs

build:packages:askui-nodejs:
  extends:
    - .build
    - .packages:askui-nodejs

release:packages:askui-nodejs:feature:
  extends:
    - .packages:askui-nodejs
  rules:
    - if: $CI_COMMIT_BRANCH != 'main'
  when: manual
  stage: release
  script:
    - apt-get update && apt-get install -y jq
    - echo $(cat package.json | jq '.name="@vqa4gui/askui-dev"') > package.json
    - npm version $(node -e "console.log(require('./package.json').version);")-${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA} --no-git-tag-version
    - npm run build
    - npm publish
