include:
  - local: /.gitlab/default.yml

.packages:askui-nodejs:
  extends: 
    - .workspace
  variables:
    WORKDIR: packages/askui-nodejs

build:packages:askui-nodejs:
  extends:
    - .build
    - .packages:askui-nodejs

release:packages:askui-nodejs:
  extends:
    - .workflow:main
    - .packages:askui-nodejs
  stage: release
  script:
    - npm run semantic-release

# TODO Enable feature builds, ideally with semantic-release

# .workflow:feature:
#   rules:
#     - if: $CI_COMMIT_BRANCH != 'main'
#   when: manual

# release:feature:
#   extends:
#       - .workflow:feature
#   stage: release
#   script:
#     - apt-get update && apt-get install -y jq
#     - echo $(cat package.json | jq '.name="@vqa4gui/askui-dev"') > package.json
#     - npm version $(node -e "console.log(require('./package.json').version);")-${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA} --no-git-tag-version
#     - npm run build
#     - npm publish
