include:
  - local: /.gitlab/.gitlab-ci.default.yml

.examples:askui-nodejs-base-example:
  extends: 
    - .workspace
  variables:
    WORKDIR: examples/askui-nodejs-base-example

build:examples:askui-nodejs-base-example:
  extends:
    - .build
    - .examples:askui-nodejs-base-example

test:examples:askui-nodejs-base-example:
  extends:
    - .workflow:mr-and-main
    - .examples:askui-nodejs-base-example
  stage: quality
  services:
    - name: registry.gitlab.com/vqa4gui/mvp/control-your-ui/runner/chrome:f740495a-feature
      alias: chrome-runner
  variables:
    WAIT_AFTER_EXECUTION: 'true'
  script:
    - npm run test
