name: CI/CD Pipeline of the askui Node.js Package
on:
  push:
    paths:
      - 'docs/**'
      - 'packages/askui-nodejs/**'
      - '.github/workflows/ci-cd-askui-nodejs.yml'
  workflow_dispatch:
    inputs:
      no-increment:
        default: false
        type: boolean
      no-npm:
        default: false
        type: boolean
env:
  NODE_VERSION: 16
jobs:
  build:
    name: Build askui Node.js package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install 
        run: npm ci
      - name: Lint 
        run: npm run lint
      - name: Test 
        run: npm run test
      - name: Build
        if: github.ref != 'refs/heads/main' && github.event_name != 'workflow_dispatch'
        run: npm run build
        working-directory: packages/askui-nodejs
  release:
    name: Release askui Node.js package
    # if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install 
        run: npm ci
      - name: Get Release Script
        id: get_release_script
        run: |
          echo "::set-output name=release_command::${{ github.event_name == 'workflow_dispatch' && 'release' || 'release:prerelease' }}"
      - name: Configure Git User
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Release
        run: npm run ${{ steps.get_release_script.outputs.release_command }} -- ${{ github.event.inputs.no-increment == 'true' && '--no-increment' || '' }} ${{ github.event.inputs.no-npm == 'true' && '--no-npm' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
  repository_dispatch_nodejs_released:
    name: Repository Dispatch askui Node.js Package Released
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch askui Node.js Package Released
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: askui_nodejs_package_released
